### PR TITLE
Spacemision writeup

### PR DESCRIPTION
**Pull request by quim0**

### CODE REVIEW

**Comment by alvarofe** [comment]
Put your name to the solution writeup-masapastosa or whatever

**Comment by alvarofe** [comment]
Moreover, put the files within the right directory

**Comment by alvarofe** [comment]
The solution are being gathered here https://github.com/radareorg/r2con-2017/tree/master/Competitions/Crackmes/Writeups so please use that directory

**Comment by radare** [comment]
now that the competitions are over feel free to submit that report unencrypted or publish a blogpost with proper formatting, images, etc.

Thanks!

**Pull request closed without merging**
